#########################################
### Spring Cloud Config Server
#########################################
spring:
  cloud:
    config:
      server:
        composite:
          - type: git
            searchPaths: '{application}'
            repos:
              TEST:
                pattern: '*TEST*'
                skipSslValidation: true
                uri: https://github.com/hkhanworks/spring-cloudembed-repo.git
                default-label: main
                searchPaths: '{application}'

# Embedded tomcat Access logs
server:
  tomcat:
    accesslog:
      enabled: true
      directory: log
      suffix: '.log'
      prefix: '${spring.application.name}-access'
      file-date-format: '.yyyy-MM-dd'
      rename-on-rotate: true
      pattern: '%a, xff=%{x-forwarded-for}i,xac=%{x-azure-clientip}i,xsc=%{X-Azure-socketIP}i - %l %u %t %r %s %b'
    basedir: './'
                
logging:
  pattern:
    file: '%d{MM-dd-yy HH:mm:ss.SSS} [%thread] %-5level [%33.33logger{5}] [${spring.application.name},%X{traceId:-},%X{spanId:-},%X{errorRef:-}]: %msg%n'
  file:
    name: './log/${spring.application.name}.log'
  logback:
    rollingpolicy:
      max-file-size: 20MB
      total-size-cap: 1GB
      max-history: 5
  level:
    root: warn
    org:
      springframework: warn